# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - maria_db:/var/lib/mysql
      - ./my.cnf:/usr/local/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: '@Password123@'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    maria_db:
